/**
 * This class is generated by jOOQ
 */
package SensorManager.SensorData;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all tables in dssforut_db
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table dssforut_db.sensor_data_registry
	 */
	public static final SensorManager.SensorData.tables.SensorDataRegistry SENSOR_DATA_REGISTRY = SensorManager.SensorData.tables.SensorDataRegistry.SENSOR_DATA_REGISTRY;
}
