/**
 * This class is generated by jOOQ
 */
package SensorManager.SensorData.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SensorDataRegistryRecord extends org.jooq.impl.UpdatableRecordImpl<SensorManager.SensorData.tables.records.SensorDataRegistryRecord> implements org.jooq.Record6<java.lang.Integer, java.sql.Date, java.sql.Time, java.lang.String, java.lang.String, java.lang.String> {

	private static final long serialVersionUID = 1227790983;

	/**
	 * Setter for <code>dssforut_db.sensor_data_registry.id</code>. 
	 */
	public void setId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>dssforut_db.sensor_data_registry.id</code>. 
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>dssforut_db.sensor_data_registry.fecha</code>. 
	 */
	public void setFecha(java.sql.Date value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>dssforut_db.sensor_data_registry.fecha</code>. 
	 */
	public java.sql.Date getFecha() {
		return (java.sql.Date) getValue(1);
	}

	/**
	 * Setter for <code>dssforut_db.sensor_data_registry.hora</code>. 
	 */
	public void setHora(java.sql.Time value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>dssforut_db.sensor_data_registry.hora</code>. 
	 */
	public java.sql.Time getHora() {
		return (java.sql.Time) getValue(2);
	}

	/**
	 * Setter for <code>dssforut_db.sensor_data_registry.dato</code>. 
	 */
	public void setDato(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>dssforut_db.sensor_data_registry.dato</code>. 
	 */
	public java.lang.String getDato() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>dssforut_db.sensor_data_registry.variable</code>. 
	 */
	public void setVariable(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>dssforut_db.sensor_data_registry.variable</code>. 
	 */
	public java.lang.String getVariable() {
		return (java.lang.String) getValue(4);
	}

	/**
	 * Setter for <code>dssforut_db.sensor_data_registry.nodo</code>. 
	 */
	public void setNodo(java.lang.String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>dssforut_db.sensor_data_registry.nodo</code>. 
	 */
	public java.lang.String getNodo() {
		return (java.lang.String) getValue(5);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record6 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row6<java.lang.Integer, java.sql.Date, java.sql.Time, java.lang.String, java.lang.String, java.lang.String> fieldsRow() {
		return (org.jooq.Row6) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row6<java.lang.Integer, java.sql.Date, java.sql.Time, java.lang.String, java.lang.String, java.lang.String> valuesRow() {
		return (org.jooq.Row6) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return SensorManager.SensorData.tables.SensorDataRegistry.SENSOR_DATA_REGISTRY.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Date> field2() {
		return SensorManager.SensorData.tables.SensorDataRegistry.SENSOR_DATA_REGISTRY.FECHA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Time> field3() {
		return SensorManager.SensorData.tables.SensorDataRegistry.SENSOR_DATA_REGISTRY.HORA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return SensorManager.SensorData.tables.SensorDataRegistry.SENSOR_DATA_REGISTRY.DATO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return SensorManager.SensorData.tables.SensorDataRegistry.SENSOR_DATA_REGISTRY.VARIABLE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field6() {
		return SensorManager.SensorData.tables.SensorDataRegistry.SENSOR_DATA_REGISTRY.NODO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Date value2() {
		return getFecha();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Time value3() {
		return getHora();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getDato();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getVariable();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value6() {
		return getNodo();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached SensorDataRegistryRecord
	 */
	public SensorDataRegistryRecord() {
		super(SensorManager.SensorData.tables.SensorDataRegistry.SENSOR_DATA_REGISTRY);
	}
}
