/**
 * This class is generated by jOOQ
 */
package com.dssforut.sensormanager.sensordata.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SensorDataRegistry extends org.jooq.impl.TableImpl<com.dssforut.sensormanager.sensordata.tables.records.SensorDataRegistryRecord> {

	private static final long serialVersionUID = 1205531436;

	/**
	 * The singleton instance of <code>dssforut_db.sensor_data_registry</code>
	 */
	public static final com.dssforut.sensormanager.sensordata.tables.SensorDataRegistry SENSOR_DATA_REGISTRY = new com.dssforut.sensormanager.sensordata.tables.SensorDataRegistry();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.dssforut.sensormanager.sensordata.tables.records.SensorDataRegistryRecord> getRecordType() {
		return com.dssforut.sensormanager.sensordata.tables.records.SensorDataRegistryRecord.class;
	}

	/**
	 * The column <code>dssforut_db.sensor_data_registry.id</code>. 
	 */
	public final org.jooq.TableField<com.dssforut.sensormanager.sensordata.tables.records.SensorDataRegistryRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>dssforut_db.sensor_data_registry.fecha</code>. 
	 */
	public final org.jooq.TableField<com.dssforut.sensormanager.sensordata.tables.records.SensorDataRegistryRecord, java.sql.Date> FECHA = createField("fecha", org.jooq.impl.SQLDataType.DATE, this);

	/**
	 * The column <code>dssforut_db.sensor_data_registry.hora</code>. 
	 */
	public final org.jooq.TableField<com.dssforut.sensormanager.sensordata.tables.records.SensorDataRegistryRecord, java.sql.Time> HORA = createField("hora", org.jooq.impl.SQLDataType.TIME, this);

	/**
	 * The column <code>dssforut_db.sensor_data_registry.dato</code>. 
	 */
	public final org.jooq.TableField<com.dssforut.sensormanager.sensordata.tables.records.SensorDataRegistryRecord, java.lang.String> DATO = createField("dato", org.jooq.impl.SQLDataType.VARCHAR.length(50), this);

	/**
	 * The column <code>dssforut_db.sensor_data_registry.variable</code>. 
	 */
	public final org.jooq.TableField<com.dssforut.sensormanager.sensordata.tables.records.SensorDataRegistryRecord, java.lang.String> VARIABLE = createField("variable", org.jooq.impl.SQLDataType.VARCHAR.length(50), this);

	/**
	 * The column <code>dssforut_db.sensor_data_registry.nodo</code>. 
	 */
	public final org.jooq.TableField<com.dssforut.sensormanager.sensordata.tables.records.SensorDataRegistryRecord, java.lang.String> NODO = createField("nodo", org.jooq.impl.SQLDataType.VARCHAR.length(50), this);

	/**
	 * Create a <code>dssforut_db.sensor_data_registry</code> table reference
	 */
	public SensorDataRegistry() {
		super("sensor_data_registry", com.dssforut.sensormanager.sensordata.DssforutDb.DSSFORUT_DB);
	}

	/**
	 * Create an aliased <code>dssforut_db.sensor_data_registry</code> table reference
	 */
	public SensorDataRegistry(java.lang.String alias) {
		super(alias, com.dssforut.sensormanager.sensordata.DssforutDb.DSSFORUT_DB, com.dssforut.sensormanager.sensordata.tables.SensorDataRegistry.SENSOR_DATA_REGISTRY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.dssforut.sensormanager.sensordata.tables.records.SensorDataRegistryRecord, java.lang.Integer> getIdentity() {
		return com.dssforut.sensormanager.sensordata.Keys.IDENTITY_SENSOR_DATA_REGISTRY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.dssforut.sensormanager.sensordata.tables.records.SensorDataRegistryRecord> getPrimaryKey() {
		return com.dssforut.sensormanager.sensordata.Keys.KEY_SENSOR_DATA_REGISTRY_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.dssforut.sensormanager.sensordata.tables.records.SensorDataRegistryRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.dssforut.sensormanager.sensordata.tables.records.SensorDataRegistryRecord>>asList(com.dssforut.sensormanager.sensordata.Keys.KEY_SENSOR_DATA_REGISTRY_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.dssforut.sensormanager.sensordata.tables.SensorDataRegistry as(java.lang.String alias) {
		return new com.dssforut.sensormanager.sensordata.tables.SensorDataRegistry(alias);
	}
}
